name: AMS Actions
description: A collection of AMS actions
author: a3.services
branding:
  icon: settings
  color: purple
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Get AMS environment
      uses: ./get
    - name: Set up AMS environment
      uses: ./set
